# Generated by Django 4.2.1 on 2023-08-06 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0002_alter_blog_img_blog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="view_count",
            field=models.IntegerField(default=0, verbose_name="количество просмотров"),
        ),
    ]
