# Generated by Django 4.2.1 on 2023-08-07 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0003_alter_blog_view_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="create_at",
            field=models.DateField(auto_now_add=True, verbose_name="Дата создания"),
        ),
    ]
